# Importa a imagem Postgres
FROM postgres:latest

# Variaveis de ambiente
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD Abacate@123
ENV POSTGRES_DB DIGITAL-UBS-DB

# Inicializacao do banco de dados
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Expoe a porta padrao PostgreSQL (5432)
EXPOSE 5432
